# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testing_proto_file.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18testing_proto_file.proto\"\"\n\x0bTextMessage\x12\x13\n\x0bsomeMessage\x18\x01 \x01(\t\"!\n\nRealNumber\x12\x13\n\x0bnumberToUse\x18\x01 \x01(\x05\"N\n\rTimeStructure\x12\x0c\n\x04hour\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12!\n\x0btimeMessage\x18\x03 \x01(\x0b\x32\x0c.TextMessage\"9\n\x0fNumberGenParams\x12\x13\n\x0b\x66loorNumber\x18\x01 \x01(\x05\x12\x11\n\tincrement\x18\x02 \x01(\x05\x32\xf0\x01\n\x12TestingRpcFeatures\x12-\n\x0b\x43urrentTime\x12\x0c.TextMessage\x1a\x0e.TimeStructure\"\x00\x12;\n\x16GenRandomNumbersStream\x12\x10.NumberGenParams\x1a\x0b.RealNumber\"\x00\x30\x01\x12\x32\n\x12SumOfStreamNumbers\x12\x0b.RealNumber\x1a\x0b.RealNumber\"\x00(\x01\x12:\n\x17TransformWordsToNumbers\x12\x0c.TextMessage\x1a\x0b.RealNumber\"\x00(\x01\x30\x01\x62\x06proto3')



_TEXTMESSAGE = DESCRIPTOR.message_types_by_name['TextMessage']
_REALNUMBER = DESCRIPTOR.message_types_by_name['RealNumber']
_TIMESTRUCTURE = DESCRIPTOR.message_types_by_name['TimeStructure']
_NUMBERGENPARAMS = DESCRIPTOR.message_types_by_name['NumberGenParams']
TextMessage = _reflection.GeneratedProtocolMessageType('TextMessage', (_message.Message,), {
  'DESCRIPTOR' : _TEXTMESSAGE,
  '__module__' : 'testing_proto_file_pb2'
  # @@protoc_insertion_point(class_scope:TextMessage)
  })
_sym_db.RegisterMessage(TextMessage)

RealNumber = _reflection.GeneratedProtocolMessageType('RealNumber', (_message.Message,), {
  'DESCRIPTOR' : _REALNUMBER,
  '__module__' : 'testing_proto_file_pb2'
  # @@protoc_insertion_point(class_scope:RealNumber)
  })
_sym_db.RegisterMessage(RealNumber)

TimeStructure = _reflection.GeneratedProtocolMessageType('TimeStructure', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTRUCTURE,
  '__module__' : 'testing_proto_file_pb2'
  # @@protoc_insertion_point(class_scope:TimeStructure)
  })
_sym_db.RegisterMessage(TimeStructure)

NumberGenParams = _reflection.GeneratedProtocolMessageType('NumberGenParams', (_message.Message,), {
  'DESCRIPTOR' : _NUMBERGENPARAMS,
  '__module__' : 'testing_proto_file_pb2'
  # @@protoc_insertion_point(class_scope:NumberGenParams)
  })
_sym_db.RegisterMessage(NumberGenParams)

_TESTINGRPCFEATURES = DESCRIPTOR.services_by_name['TestingRpcFeatures']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTMESSAGE._serialized_start=28
  _TEXTMESSAGE._serialized_end=62
  _REALNUMBER._serialized_start=64
  _REALNUMBER._serialized_end=97
  _TIMESTRUCTURE._serialized_start=99
  _TIMESTRUCTURE._serialized_end=177
  _NUMBERGENPARAMS._serialized_start=179
  _NUMBERGENPARAMS._serialized_end=236
  _TESTINGRPCFEATURES._serialized_start=239
  _TESTINGRPCFEATURES._serialized_end=479
# @@protoc_insertion_point(module_scope)
